{% set name = "fileseq" %}
{% set version = "2.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 81fe1b49f58a7920cc76adc42ea0e369897c0bed5d17798704731688678d2897

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - fileseq
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/justinfx/fileseq
  summary: A Python library for parsing frame ranges and file sequences commonly used in VFX and Animation applications.
  doc_url: https://pythonhosted.org/Fileseq/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rebx
    - justinfx
