{% set name = "fileseq" %}
{% set version = "3.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bfcd5094d278804345a07198e0ce79a3bb6642342257ea0b51c9e0f6c655b3b3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - fileseq
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/justinfx/fileseq
  summary: A Python library for parsing frame ranges and file sequences commonly used in VFX and Animation applications.
  doc_url: https://pythonhosted.org/Fileseq/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rebx
    - justinfx
