{% set name = "fileseq" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Fileseq-{{ version }}.tar.gz
  sha256: ed5ffae34b28dd7819f20dd1c4086c7f2c7b365714e78ae9a8d825ceb34109f4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - typing-extensions
    - python >=3.6

test:
  imports:
    - fileseq
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/justinfx/fileseq
  summary: A Python library for parsing frame ranges and file sequences commonly used in VFX and Animation applications.
  doc_url: https://pythonhosted.org/Fileseq/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rebx
    - justinfx
