{% set name = "fileseq" %}
{% set version = "1.13.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Fileseq-{{ version }}.tar.gz
  sha256: f11d191add45b56924f2fb439d03502992fe5485fc6eb849a81e7f2f3fb3d584

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - future
    - python >=2.7

test:
  imports:
    - fileseq
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/justinfx/fileseq
  summary: A Python library for parsing frame ranges and file sequences commonly used in VFX and Animation applications.
  doc_url: https://pythonhosted.org/Fileseq/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rebx
    - justinfx
