{% set name = "fileseq" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Fileseq-{{ version }}.tar.gz
  sha256: b32a99e63086adb7d8a8be4a69b48bab6739ae233fbf8c67ff280141c42d98ff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - future
    - python >=2.7

test:
  imports:
    - fileseq
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/justinfx/fileseq
  summary: A Python library for parsing frame ranges and file sequences commonly used in VFX and Animation applications.
  doc_url: https://pythonhosted.org/Fileseq/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rebx
    - justinfx
